### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by sschueller** [cnlab-software-ag/passwortcheck#1]
Hi,

I would be nice to be able to use this as a library similar to https://github.com/dropbox/zxcvbn/ since zxcvbn is no ideal for non English sites at this time.

**Comment by dsb-zh** [comment]
Hi

The Passwortcheck is subject to the [BSD 2-Clause](https://github.com/cnlab-software-ag/passwortcheck/blob/master/license.txt) and can be used accordingly. Would this suite your needs?

Kind regards
DSB

**Comment by sschueller** [comment]
Hi,

What I mean is it would be useful to be able to use your password checker on our sites. This means it would need be packaged as a library so we can use via npm and webpack. The current source is an angular app which is not suitable for other sites to use.

Regards,

Stefan

**Comment by dsb-zh** [comment]
Hi Stefan

Thank you for your interest and feedback regarding the Passwortcheck. Currently there is no plan to provide the Passwortcheck as an npm and webcheck library. However, we will add it to our issue list. Unfortunately we cannot state if and when the functionality will be available. Thank you for your understanding.

Kind regards
Bernhard

**Comment by cnlab-software-ag** [comment]
Hi

We updated the application with a distinctive branch to allow the integration of the password checker in an iframe.
It's still not a standalone library that can be added as dependency, but at least is should work without a lot of modifications.

Regards,
Lukas
